Add `github` option for `--ci` in scaffold package tests
wp-cli/scaffold-package-command pull request #237
Opened 2024-03-20 09:57 UTC by ernilambar

Fixes: https://github.com/wp-cli/scaffold-package-command/issues/217

* Add `github` option for `--ci` argument in `scaffold package-tests`
* Two files are added for this CI.
- `behat.yml` - Same file from the root is copied
- 'testing.yml' - Template file is kept at `dot-github/workflows` folder. This will be copied to `.github/workflows`

2024-03-20 13:43 UTC, wojtekn approved these changes
The change looks clear, and works fine:

```
% vendor/bin/wp scaffold package-tests wp-cli-shim --ci=github 
Success: Created package test files.
```

2024-03-21 08:07 UTC, danielbachhuber approved these changes

2024-03-21 08:09 UTC, danielbachhuber requested changes
Can you add some basic tests for this?

2024-03-21 08:09 UTC, danielbachhuber commented on dot-github/workflows/testing.yml
> +name: Testing
This should live in `templates/`, no?

2024-03-21 08:09 UTC, danielbachhuber commented on dot-github/workflows/testing.yml
> +        php-version: ['8.0', '7.4']
Let's add 8.2 here too

2024-03-21 11:50 UTC, ernilambar commented
@danielbachhuber PR has been updated.

2024-03-23 10:40 UTC, danielbachhuber approved these changes
Thanks @ernilambar !

2024-03-23 10:41 UTC, merged